server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
    pool.max-idle: 8
    pool.min-idle: 1
    pool.max-active: 8
    pool.max-wait: -1


mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.example.demo.entity


logging:
  config: classpath:log/logback-spring.xml
  level:
    com:
      example:
        demo:
          controller: debug
          mapper: debug
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n  '
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n  '




  redis: # redis配置
    database: 0         # Redis数据库索引（默认为0）
    host: 127.0.0.1     # Redis服务器地址
    password:
    port: 6379           # Redis服务器连接端口
    timeout: 30000
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）


