server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
    pool.max-idle: 8
    pool.min-idle: 1
    pool.max-active: 8
    pool.max-wait: -1


mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.example.demo.entity



logging:
  level:
    com:
      example:
        mapper: debug
